### ISSUE TITLE
Questions about modeling and simulation with Python

### ISSUE THREAD

**Issue by garciamsu** [ESDLMapEditorESSIM/docker-toolsuite#10]
Hi Edwin, I'm studying the API and doing some simple exercises to understand ESDL, but I have some questions.

* What is the difference between working with pyecore and pyESDL? When should I apply each?

* I need to model a solar panel and an electrical consumer, using the environment profiles to introduce the irradiance. How do I link in the environment profile with the PV panel in python? . On the other hand, what attributes do I use to obtain the potential in Watt of the solar panel based on the irradiance and the real power delivered by the panel to the load?

* When reviewing the battery it only has one input port, how can I analyze and change its dynamics in python as a producer and then as a consumer?

* The objective of my research project is to model and study in ESDL some  DER with ESS, PV, utility grid, ... that coordinate with each other to activate or deactivate to satisfy demand, according to certain hypotheses and incorporating a new strategy emergent control. What is the simplest modeling that you recommend to implement it in ESDL with python?

* In the ESDL graphical editor, can I incorporate indicators or measurements to visualize the change of the variables of interest? While the simulation is running, as well as visualize in real time the enabling or disabling of the assets ???

* I am getting this problem when I upload the CSV file of the irradiance in environment profiles (Edit/Enviromental profiles/irradiance), at first it seems to work but when I save the .esdl file locally or in the Drive of my account, said information does not appear when trying to load again.

* Is there a standard library of KPIs by type of assets?

Thanks

Marcel

**Comment by edwinmatthijssen** [comment]
Hi Marcel,

Most of these question do not relate to this docker-toolsuite project and should be posed in the other relevant repositories. This is necessary such that others can also find these issues there and learn from them. Furthermore it's much appreciated if you pose one question per issue. This makes it easier to answer and later on easier to find if you give the issues proper titles.

However I will try to answer (some of) your questions shortly or give you some pointers:

- pyEcore is the library that translates the ESDL ECore model into python classes that are used in pyESDL. So pyEcore is very generic and has nothing to do with ESDL. If you want to write python code to deal with ESDL it's very wise to also have a look at the pyEcore documentation. Furthermore, the pyESDL documentation and tutorials might be useful.
  - https://github.com/pyecore/pyecore
  - https://pyecore.readthedocs.io/
  - https://modeling-languages.com/pyecore-python-eclipse-modeling-framework/
  - https://pypi.org/project/pyESDL/
  - https://energytransition.gitbook.io/esdl/software-development/integration-with-python-and-pyecore
  - https://github.com/EnergyTransition/ESDL-PyEcore-Tutorial/blob/master/ESDLTutorials.ipynb
 
- If you want to calculate power from the solar irradiance, the PVLib library might be the thing you're looking for:
  - https://pvlib-python.readthedocs.io/

- ESDL supports as many InPorts and OutPorts as you need. I think you're referring in your question to the ESDL MapEditor, which by default gives a battery an InPort. The InPort and OutPort are defined such that the direction of the 'positive energy flow' is determined. However, the energy can flow in the other direction too, only then the sign will be negative. It's up to you to decide on if you want to add a second port to a battery or allow both charging and discharging using only one port.

- Your 4th question is really to open for me. There's no simple answer to that question I think.

- No, this is not possible at the moment. There's no "live link" between a running simulation and the ESDL MapEditor. There are some possibilities to visualize the outcomes of simulations on the map, but this is in an experimental stage and not yet properly documented. 

- This seems to be a bug indeed (if I understand your question properly). I will have to look at this in more detail whenever I find time.

- No, there's no standardized KPI list at all, so for sure not per type of asset. If you know about any standardized KPI frameworks specific for the energy domain, we're interested to hear about it. For the time being you can define your own set of KPIs. This gives too much freedom and doesn't result in proper interoperability between models/tools (the main reason for developing ESDL). But we definitely want to improve this in the future.

**Comment by garciamsu** [comment]
Hi Edwin, thank you very much for the guidance.

Please tell me the correct repositories to use for each question, so I can proceed to reorganize them.

Thank you

Marcel

**Comment by garciamsu** [comment]
Hello Edwin, let me tell you that I will soon finish the article to send it to the Journal for review. I have some concerns but I will do them in separate tickets
