### ISSUE TITLE
Empty dropdown menu and error in Python backend

### ISSUE THREAD

**Issue by theogiraudet** [ESDLMapEditorESSIM/docker-toolsuite#11]
Hello,

I want to try the the ESDL MapEditor, for that I have followed the guide presents in the README of this repository to install the whole infrastructure. All the steps before step 7 work pretty great but when I am in the ESDL MapEditor page, the dropdown menues at the top-left corner are empty. The loader at the center of the screen turns indefinitely.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/28688370/217505372-847743ff-2e4a-46ae-80b4-6f4ce4198f1a.png">

I have errors on the browser console:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/28688370/217502320-3d0512e9-0afe-47b1-8fe6-f579461520d6.png">

When I click on the dropdown menu:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/28688370/217502686-f09cfd5a-1a81-42b7-819f-c5c13560b59c.png">

In the backend-side, I have some errors too:

![image](https://user-images.githubusercontent.com/28688370/217503319-a30d6aab-0d13-4715-9323-9169816d7436.png)

![image](https://user-images.githubusercontent.com/28688370/217503488-da509e2b-7ebe-4fda-befe-506db7876c03.png)

I have checked a bit the code, but the version 22.10.0 isn't tagged on the [ESDL MapEdditor Github](https://github.com/ESDLMapEditorESSIM/esdl-mapeditor). The two problems are caused by the same function:

https://github.com/ESDLMapEditorESSIM/esdl-mapeditor/blob/6d3d84086c027a2f639032fc088bd89330273523/extensions/settings_storage.py#L94-L103

But I don't really understand why, because the functions that call this one seem to check before if the setting exists for the specified user:

https://github.com/ESDLMapEditorESSIM/esdl-mapeditor/blob/7deb97bd441c7589b490eb53d9e8744b97283402/src/view_modes.py#L378-L386

So I don't really know if it's because I may not have checked the right version of the code or if it's due to something else like a bad configuration.

Some information about my setup:
- I am on Windows 11 and I tried to follow the installation guide with Windows and with WSL (Ubuntu).
- Version of Docker: 20.10.22
- Version of ESDL-mapeditor: latest (22.10.0 at this time)
- I am in Mozilla Firefox

**Comment by ewoudwerkman** [comment]
Hi Theo,

Thanks for this issue. We ran into this issue too, recently. It has to do with the settings storage and view modes trying to write and read to the mongo database simultaneously (i.e. a concurrency issue), which we haven't found a solution for yet.
A workaround is editing the settings documents in the MongoDB directly (two entries are created for the same user, instead of one, deleting one will solve the issue, or merging both will also work). You can use any mongoDB editor to edit this.

**Comment by theogiraudet** [comment]
Thank you very much for your quick answer. Your solution works perfectly.
