### ISSUE TITLE
Passwords in initdb do not use the env vars in .env

### ISSUE THREAD

**Issue by lfse-slafleur** [ESDLMapEditorESSIM/docker-toolsuite#17]
**Branch**: infra-update

https://github.com/ESDLMapEditorESSIM/docker-toolsuite/blob/infra-update/BaseInfrastructure/postgres/init-database.sh

Still hardcoded to `password` while .env has references to set these passwords: https://github.com/ESDLMapEditorESSIM/docker-toolsuite/blob/infra-update/BaseInfrastructure/.env.template

**Comment by TNO-SlaFleur** [comment]
Fixed by #19

**Comment by ewoudwerkman** [comment]
Merged and fixed by @lfse-slafleur. Thanks!
