### ISSUE TITLE
Baseinfrastructure/docker-compose.yml uses different postgres env vars names than .env-template

### ISSUE THREAD

**Issue by lfse-slafleur** [ESDLMapEditorESSIM/docker-toolsuite#18]
**Branch**: infra-update

The `docker-compose.yml` uses the `POSTGRES_DB_` prefix while the `.env-template` uses the `POSTGRES_` prefix.

https://github.com/ESDLMapEditorESSIM/docker-toolsuite/blob/infra-update/BaseInfrastructure/docker-compose.yml
https://github.com/ESDLMapEditorESSIM/docker-toolsuite/blob/infra-update/BaseInfrastructure/.env.template

**Comment by TNO-SlaFleur** [comment]
Fixed by #19

**Comment by ewoudwerkman** [comment]
Merged and fixed, Thanks for the pull request.
