### ISSUE TITLE
Error message during step 2.

### ISSUE THREAD

**Issue by MaximUUeng** [ESDLMapEditorESSIM/docker-toolsuite#2]
Hi,

During step 2 (Importing the keycloak settings for the MapEditor) while installing on a local machine the below error occurs.
Similar messages are displayed for other ports. Keycloak can be accessed via the local adress but the esdl realm is not displayed. 
Any suggstions on how to resolve this would be greatly appreciated. 

11:13:32,103 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service org.wildfly.undertow.listener.default: org.jboss.msc.service.StartException in service org.wildfly.undertow.listener.default: Address already in use /127.0.0.1:8080
        at org.wildfly.extension.undertow@20.0.1.Final//org.wildfly.extension.undertow.ListenerService.start(ListenerService.java:209)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
        at org.jboss.msc@1.4.11.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by edwinmatthijssen** [comment]
It could be that you’re running other software that uses port 8080. Could you check that?

However, we have one more user with this error...   I will dive into this soon (probably tomorrow). Could you give us some more context?  What operating system? What are the exact steps you’ve followed? What docker version? What docker-compose version? And so on...   Where in step 2 exactly did you receive this error?

**Comment by ewoudwerkman** [comment]
During step 2, you start another keycloak to import the configuration using, right? And this command goes wrong?:
```
docker exec -it keycloak /opt/jboss/keycloak/bin/standalone.sh \
  -Djboss.socket.binding.port-offset=100 \
  -Dkeycloak.profile.feature.upload_scripts=enabled \
  -Dkeycloak.migration.action=import \
  -Dkeycloak.migration.provider=singleFile \
  -Dkeycloak.migration.strategy=OVERWRITE_EXISTING \
  -Dkeycloak.migration.file=/tmp/esdl-mapeditor-realm.json
```
The ```-Djboss.socket.binding.port-offset=100 ``` is important here, as it starts the importing keyclock on port 8080 + 100 = 8180. Can you check if that happens?

**Comment by MaximUUeng** [comment]
Thanks for your replies. 

I am running Windows 10 Enterprise. Version 10.0.18363
Docker engine: v20.10.5 

First I open a command window in the base infrastructure folder and perform the docker-compose up command.
In docker I can see the base infrastructure starting up and running. At this point I can reach keycloack at http://127.0.0.1:8080/

![image](https://user-images.githubusercontent.com/84572762/120485971-e47f2700-c3b4-11eb-9350-fef53eabee16.png)

Next I open a new command prompt as the first cmd doesnt allow new input and perform:

**Comment by ewoudwerkman** [comment]
Ah, I think the problem is that the script is created to run in a unix (bash) shell instead of a windows command prompt, therefore creating issues with the '\' and multiple lines. You can try to put the whole command on one line or install Git bash or use Windows Subsystem for Linux to get a bash shell in Windows.

**Comment by MaximUUeng** [comment]
Thanks! This worked. 

In the windows command shell I used the following command all on the same line:

docker exec -it keycloak /opt/jboss/keycloak/bin/standalone.sh -Djboss.socket.binding.port-offset=100 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.migration.file=/tmp/esdl-mapeditor-realm.json

**Comment by ewoudwerkman** [comment]
Glad it helped. Thanks for reporting: we've updated the documentation to clarify this.
