### ISSUE TITLE
Keycloak URL in setup is incorrect

### ISSUE THREAD

**Issue by lfse-slafleur** [ESDLMapEditorESSIM/docker-toolsuite#20]
**Branch**: infra-update

`http://localhost:8080` should be `http://localhost:8080/auth/` at step 3 'creating user accounts'

**Comment by edwinmatthijssen** [comment]
The first URL works too, and is automatically redirected to the second if I'm right. Or does this issue refer to the new keycloak version and did this behavior change?

**Comment by ewoudwerkman** [comment]
Yes, new keycloak does not use /auth anymore, but can be configured to use it, but misses redirect to /auth.
For backwards compatibility I added the /auth in the keycloak config.

**Comment by TNO-SlaFleur** [comment]
I can confirm that `http://localhost:8080` does not redirect to `http://localhost:8080/auth`. It shows an error that the resource cannot be found which caused me to think I missed some configuration parameter and Keycloak wasn't functioning correctly yet. However, just going to the right url `http://localhost:8080/auth` was all I needed to do.

**Comment by TNO-SlaFleur** [comment]
Fixed in #19

**Comment by ewoudwerkman** [comment]
Merged, but the caddy part is not included. Manually go to the /auth endpoint is now what is documented in the README.md
