### ISSUE TITLE
Keycloak doesn't start correctly on docker-compose up

### ISSUE THREAD

**Issue by JochemBoersma** [ESDLMapEditorESSIM/docker-toolsuite#4]
**Context:**
docker-compose up on my local machine (linux containers)

**Following error occurs in bringing up the services:**
keycloak    | 09:19:31,682 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "microprofile-metrics-smallrye")]): java.lang.NullPointerException

**At restart, the following error occurs:** 
keycloak    | User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'

Bringing the compose down, and removing all volumes before a restart doesn't solve.
Any help or workaround would be appreciated.

**Comment by edwinmat** [comment]
This is a known KeyCloak issue that sometimes occur (We don't really understand yet when and why). Could you try the solution provided by the first answer in this stackexchange post: https://stackoverflow.com/questions/59599620/keycloak-8-user-with-username-admin-already-added.

**Comment by JochemBoersma** [comment]
Tried it according the stack-overflow solution, but received similar error. Both on my VM (Ubuntu 20.04) and on my laptop (Win10), and I get the same error..

From outside, in webbrowser, it returns this error: `503 - Service Unavailable`

The pgadmin server is running (and accessable from outside) but empty.

Do you have an work-around? No problem for me to install the keycloak software outside the docker-stack, but wondering if this works anyways...

The error log:
```
keycloak    | 20:46:07,209 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "microprofile-metrics-smallrye")]): java.lang.NullPointerException
keycloak    |   at org.wildfly.extension.microprofile.metrics-smallrye@20.0.1.Final//org.wildfly.extension.microprofile.metrics.MicroProfileMetricsSubsystemAdd$2.execute(MicroProfileMetricsSubsystemAdd.java:86)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:999)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:743)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:467)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1413)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:527)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:515)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:477)
keycloak    |   at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:451)
keycloak    |   at org.jboss.as.server@12.0.3.Final//org.jboss.as.server.ServerService.boot(ServerService.java:404)
keycloak    |   at org.jboss.as.controller@12.0.3.Final//org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
keycloak    |   at java.base/java.lang.Thread.run(Thread.java:834)
keycloak    |
keycloak    | keycloak exited with code 1
```

**Comment by JochemBoersma** [comment]
reminds me of the following cartoon:
![before-devops-after-devops](https://user-images.githubusercontent.com/17458761/137125033-949b2e19-7994-4ecc-9cf1-bad17a3bd510.png)

Next week I will give it another try, with your suggestions. Thanks for them anyway.
