### ISSUE TITLE
Problem with Current profiles

### ISSUE THREAD

**Issue by garciamsu** [ESDLMapEditorESSIM/docker-toolsuite#6]
Hello, when I try to load the profiles I get the following error:

**"Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."**

I'm using docker (version 20.10.17, build 100c701) and docker-compose (v2.6.0)

Thank you

Marcel

**Comment by garciamsu** [comment]
Hi Ewoud, thank you for your answer. Below I describe more details of the problem presented and the context.

- My SO is Linux esdl 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64
- These are the active processes in docker (sudo docker ps)

CONTAINER ID   IMAGE                                        COMMAND                  CREATED       STATUS          PORTS                                                                                                                             NAMES
c1bff99a34d6   jboss/keycloak                               "/opt/jboss/tools/do…"   11 days ago   Up 24 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 0.0.0.0:8443->8443/tcp, :::8443->8443/tcp                                              keycloak
850459b3a01b   dpage/pgadmin4                               "/entrypoint.sh"         11 days ago   Up 24 minutes   443/tcp, 0.0.0.0:5050->80/tcp, :::5050->80/tcp                                                                                    pgadmin
a3059f696303   postgis/postgis:12-master                    "docker-entrypoint.s…"   3 weeks ago   Up 24 minutes   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp                                                                                         postgres
3622f0074678   esdlmapeditoressim/esdl-drive:latest         "/opt/ol/wlp/bin/ser…"   3 weeks ago   Up 49 seconds   0.0.0.0:9080->9080/tcp, :::9080->9080/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp                                              esdl-drive
121c0fc1c067   esdlmapeditoressim/cdo-server:latest         "/bin/sh -c 'java -j…"   3 weeks ago   Up 50 seconds   0.0.0.0:2036->2036/tcp, :::2036->2036/tcp                                                                                         cdo-server
097372f79108   esdlmapeditoressim/panel-service:latest      "gunicorn influxdbgr…"   3 weeks ago   Up 2 minutes    0.0.0.0:3400->5000/tcp, :::3400->5000/tcp                                                                                         panel-service
f4f28b40bbff   esdlmapeditoressim/boundary-service:latest   "/bin/sh -c 'cd /usr…"   3 weeks ago   Up 2 minutes    0.0.0.0:4002->4002/tcp, :::4002->4002/tcp                                                                                         boundary-service
ba119d99fb18   esdlmapeditoressim/nats-server:latest        "docker-entrypoint.s…"   3 weeks ago   Up 4 minutes    0.0.0.0:4222->4222/tcp, :::4222->4222/tcp, 0.0.0.0:6222->6222/tcp, :::6222->6222/tcp, 0.0.0.0:8222->8222/tcp, :::8222->8222/tcp   essim-nats-1
4fcf23210206   esdlmapeditoressim/esdl-mapeditor:latest     "/bin/sh -c 'cd /usr…"   4 weeks ago   Up 2 minutes    0.0.0.0:8111->8111/tcp, :::8111->8111/tcp                                                                                         esdl-mapeditor
3ad07d547338   esdlmapeditoressim/essim:latest              "/bin/sh -c 'java -X…"   4 weeks ago   Up 4 minutes    0.0.0.0:8112->8112/tcp, :::8112->8112/tcp                                                                                         essim-essim-engine-1
05b0d2e41bf7   grafana/grafana:7.4.5                        "/run.sh"                4 weeks ago   Up 5 minutes    0.0.0.0:3000->3000/tcp, :::3000->3000/tcp                                                                                         grafana
7c82483c97a4   influxdb:1.7                                 "/entrypoint.sh infl…"   4 weeks ago   Up 5 minutes    0.0.0.0:8086->8086/tcp, :::8086->8086/tcp, 0.0.0.0:8088->8088/tcp, :::8088->8088/tcp                                              influxdb
f190e4fe7666   mvertes/alpine-mongo                         "/root/run.sh mongod…"   4 weeks ago   Up 5 minutes    0.0.0.0:27017->27017/tcp, :::27017->27017/tcp, 28017/tcp

- I followed step 8, but my GUI is different from the one presented in the tutorial. [https://drive.google.com/file/d/1tTecWWgfV-oPtXVwHvP0Vu3Gp753wQm1/view?usp=sharing](url) The exact procedure is carried out and no error is generated, but some fields are blank, such as Embed URL, and the graph is not shown. Furthermore, when pressing test, nothing happens either.
- Delete all the created profiles and load them again, and the error does not appear but it does not show any graph and the "Play" button in the left side menu does not appear either.

**Comment by edwinmat** [comment]
Hi Marcel,

From what I read above, it looks like you did not properly configure the panel service (the service that generates the graphs within the MapEditor). The Embed URL is also generated by this panel service, during the upload process of the profile data. 

Step 5 of the installation instructions tells you how to create the API key in Grafana and where to put it in the panel service config. Did you succeed in that process?  If you login to grafana and go to API keys in the settings, do you see an API keys listed?

Could you maybe also post the docker-compose logs (of at least the MapEditor and PanelService containers) during the upload process of profile data in step 8?

Regards,
Edwin

**Comment by garciamsu** [comment]
Hi Edwin, thank you very much for the help. Sure enough, I had made a mistake in step 5.

I have already managed to install it and am working on my research paper with such an excellent tool.

**Comment by edwinmatthijssen** [comment]
No problem at all, glad we could help….    And good to hear that you’re enthusiastic about the tool. Could you tell a little more about the research you’re doing? And would it be possible to receive a link to the paper once it is published? Would be great to see what people are doing with our tooling! And if that’s allowed we could also add a reference to it on our website…

**Comment by garciamsu** [comment]
Hi Edwin, our research is focused around the concept of emergent control, and we are using the ESDL tool to model smartgrid and microgrid; We will gladly send you the article once it is published.

Marcel García & Jose Aguilar (2022) Emergent control in the context of
industry 4.0, International Journal of Computer Integrated Manufacturing, 35:3, 247-262, DOI:
10.1080/0951192X.2021.1992653
