### ISSUE TITLE
Problems with EDR

### ISSUE THREAD

**Issue by garciamsu** [ESDLMapEditorESSIM/docker-toolsuite#8]
Hello please your help regarding EDR data repository

The information data available in EDR is very limited when accessing the portal https://edr.hesi.energy/ and does not match what is presented in the documentation https://energytransition.gitbook.io/esdl/esdl-based-tools /energy-data-repository

Also, the login icon located at the top right does not work.

Thank you

**Comment by edwinmatthijssen** [comment]
Yes this is correct!  We’re currently redeveloping the whole EDR with new features (like logging in and having a personal storage space). At the moment logging in does not work yet indeed. 

The screenshots you refer too are still from the old implementation and will be updated some day. The challenge now is to find projects/budget and time to work on this….

I’m also planning to open source the code of the EDR tool itself some day, such that people can install their own version. But that will take some time….

**Comment by garciamsu** [comment]
OK thank you very much. Now that I understand the current state of the EDR, I am going to work with my data set from external sources to continue with my work.
