### ISSUE TITLE
Python API for ESDL

### ISSUE THREAD

**Issue by garciamsu** [ESDLMapEditorESSIM/docker-toolsuite#9]
Hello, I am analyzing new distributed control strategies that allow me to coordinate different producers, for this I plan to use python.

Already reviewed these documents

https://github.com/EnergyTransition/ESDL-PyEcore-Tutorial/blob/master/ESDLTutorials.ipynb
https://github.com/redekok/startanalyse-esdl/blob/master/parse_data.py

But I need to know the Python API for ESDL where all the parameters of the system models are explained in detail. Any suggestion? Where can I find more information?

I plan to generate the ESLD with the graphical interface and then read and write from python to generate the analyses.

Thank you

**Comment by edwinmatthijssen** [comment]
Have a look at at least these things:
- pyESDL pip package: https://pypi.org/project/pyESDL/
- ESDL language reference: https://energytransition.github.io/
- Example projects on our github page:
  - parsing an ESDL and retreiving topology and geometry information out of it: https://github.com/EnergyTransition/ESDL-Geometry-Information
  - Excel to ESDL: https://github.com/EnergyTransition/excel-2-esdl
  - Building a Flask service that receives and ESDL and calculate some things: https://github.com/EnergyTransition/Flask-ESDL-service
  - shapefile to ESDL: https://github.com/EnergyTransition/shapefile-2-esdl

**Comment by garciamsu** [comment]
OK thank you very much. This information is what I needed, I'm going to review it and I'll ask you if I have any questions.

Cheers,
